# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Tomo Furutani
tagline:          
description:      
url:              "http://oldvalley49.github.io"
baseurl:          ""

author:
  name:           'Tomo Furutani'
  url:            https://oldvalley49.github.io

# paginate:         5

# Custom vars
# version:          2.1.0

github:
  repo:           https://github.com/oldvalley49

kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: false